<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6M9B03E" ignored="2" name="Default test(failed)" tests="2" failures="2" timestamp="2019-11-19T16:35:59 EST" time="0.079" errors="0">
  <testcase name="test2" time="0.016" classname="demo.TestNGRetryFailedDemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at demo.TestNGRetryFailedDemo.test2(TestNGRetryFailedDemo.java:21)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.007" classname="demo.TestNGRetryFailedDemo">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase name="test1" time="0.0" classname="demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
